### ISSUE TITLE
TypeError: db.get is not a function

### ISSUE THREAD

**Issue by ghost** [sudis/mongosha-economy#1]
Any command I do I get the error "TypeError: db.get is not a function"

Here is the full error for the bank command but it's all the same for the other commands too.

`(node:9592) UnhandledPromiseRejectionWarning: TypeError: db.get is not a function
    at Object.module.exports.run (C:\Users\ashto\Desktop\mongosha-economy-main\commands\bank\bank.js:51:29)
    at Client.module.exports (C:\Users\ashto\Desktop\mongosha-economy-main\events\message.js:58:7)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:384:31)
    at WebSocketShard.onPacket (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\ws\lib\websocket.js:825:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (C:\Users\ashto\Desktop\mongosha-economy-main\node_modules\ws\lib\receiver.js:78:10)
(node:9592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)`

**Comment by sudis** [comment]
Hello! The "Mongosha" module has been changed. So this functions not useable. You can fix this stuation but you must learn new module. Sincerely.
